name: build macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake -S . -B build
    - name: build
      run: cmake --build build --parallel 2
    - name: test
      run: cd build; ctest -j 2