name: build ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake -S . -B build
    - name: build
      run: cmake --build build --parallel 2
    - name: test
      run: cd build; ctest -j 2